# Kaggle Competition

### FIA

<br>


Dataset:

2018-05-04

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns; sns.set_style('white')

%matplotlib inline

In [ ]:
# read data
data = pd.read_csv(
    'placeholder.csv',
    econding='iso-8859-1',
    
)

In [11]:
data['target'].value_counts(normalize=True)

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [ ]:
# separate test and train data
from sklearn.model_selection import train_test_split

X = data.iloc[:,0:-1]
y = data.iloc[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=433)

In [12]:
#### temp - testing with iris dataset

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=42)

In [13]:
# scaling
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train) # fitted on train data only

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

### baseline

In [23]:
from sklearn.linear_model import LogisticRegression

logit = LogisticRegression(C=1e5)
logit.fit(X_train, y_train)
y_hat = logit.predict(X_test)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(confusion_matrix(y_test, y_hat))
print()
print(classification_report(y_test, y_hat))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30

